import { Button, Card, Col, Descriptions, Drawer, Empty, Flex, Form, Input, Modal, Radio, Row, Select, Space, Switch, Tag, Typography } from "antd";
import type { AgentFormValues, AgentRecord, AgentTeamFormValues, AgentTeamRecord, ApprovalRecord, ConnectorFormValues, ConnectorKind, KnowledgeFormValues, RiskLevel, TaskFormValues } from "../../domain/workbench";

const { Paragraph, Text, Title } = Typography;
const risk: Record<RiskLevel, [string, string]> = { low: ["success", "低风险"], medium: ["warning", "中风险"], high: ["error", "高风险"] };

export function ApprovalDrawer({ open, approvals, onClose, onRespond }: { open: boolean; approvals: ApprovalRecord[]; onClose: () => void; onRespond: (id: string, decision: ApprovalRecord["status"]) => void | Promise<void> }) {
  const pending = approvals.filter((item) => item.status === "pending");
  return <Drawer title="审批请求" open={open} onClose={onClose} size={520}>{pending.length ? <Space orientation="vertical" size={16} className="full-width">{pending.map((item) => <Card key={item.key} className="approval-card"><Space wrap><Tag color={risk[item.risk][0]}>{risk[item.risk][1]}</Tag><Tag>{item.source}</Tag></Space><Title level={4}>{item.title}</Title><Paragraph>{item.reason}</Paragraph><Descriptions column={1} bordered size="small"><Descriptions.Item label="能力"><Space wrap>{item.capabilities.map((capability) => <Tag key={capability}>{capability}</Tag>)}</Space></Descriptions.Item></Descriptions><Flex justify="end" gap={8} className="drawer-actions"><Button onClick={() => void onRespond(item.key, "denied")}>拒绝</Button><Button type="primary" onClick={() => void onRespond(item.key, "allowed")}>允许本次</Button></Flex></Card>)}</Space> : <Empty description="暂无待审批动作" />}</Drawer>;
}

export function PluginModal({ open, onCancel, onOk }: { open: boolean; onCancel: () => void; onOk: () => void }) {
  return <Modal title="启动插件：自媒体周更" open={open} onCancel={onCancel} onOk={onOk} okText="授权并启动"><Paragraph type="secondary">确认本次运行将使用的能力。</Paragraph><Space orientation="vertical" className="full-width">{[["network:read", "读取热榜与竞品页面", true], ["knowledge:read", "检索品牌与 SOP", true], ["files:write", "写入 artifact", true], ["browser:input", "写入公众号草稿箱", false]].map(([capability, text, enabled]) => <Flex key={String(capability)} align="center" gap={12} className="capability-row"><Switch defaultChecked={Boolean(enabled)} /><Text><Text code>{capability}</Text> {text}</Text></Flex>)}</Space></Modal>;
}

export function TaskModal({ open, agents, teams, onCancel, onCreate }: { open: boolean; agents: AgentRecord[]; teams: AgentTeamRecord[]; onCancel: () => void; onCreate: (values: TaskFormValues) => void | Promise<void> }) {
  const [form] = Form.useForm<TaskFormValues>();
  const type = Form.useWatch("targetType", form) ?? "agent_team";
  const options = type === "agent" ? agents.map((item) => ({ value: item.key, label: item.name })) : type === "plugin" ? ["自媒体周更插件", "代码需求实现插件", "产品上线宣传包"].map((value) => ({ value, label: value })) : teams.length ? teams.map((item) => ({ value: item.key, label: item.name })) : [{ value: "team_content_ops", label: "自媒体内容团队" }];
  return <Modal title="新建任务" open={open} onCancel={onCancel} onOk={() => form.submit()} okText="创建任务" destroyOnHidden><Form form={form} layout="vertical" initialValues={{ title: "公众号周更：AI Agent 工作流", targetType: "agent_team", targetId: teams[0]?.key ?? "team_content_ops", priority: "normal", requiresApproval: true }} onValuesChange={(changed) => { if (changed.targetType) form.setFieldValue("targetId", changed.targetType === "agent" ? agents[0]?.key : changed.targetType === "plugin" ? "自媒体周更插件" : teams[0]?.key ?? "team_content_ops"); }} onFinish={(values) => { void onCreate(values); form.resetFields(); }}><Form.Item label="任务标题" name="title" rules={[{ required: true }]}><Input /></Form.Item><Form.Item label="任务说明" name="prompt" rules={[{ required: true }]}><Input.TextArea rows={4} /></Form.Item><Row gutter={12}><Col span={12}><Form.Item label="目标类型" name="targetType"><Select options={[{ value: "agent_team", label: "Agent Team" }, { value: "agent", label: "单 Agent" }, { value: "plugin", label: "Workflow Plugin" }]} /></Form.Item></Col><Col span={12}><Form.Item label="运行目标" name="targetId"><Select options={options} /></Form.Item></Col></Row><Row gutter={12}><Col span={12}><Form.Item label="优先级" name="priority"><Radio.Group optionType="button"><Radio value="normal">普通</Radio><Radio value="high">高</Radio></Radio.Group></Form.Item></Col><Col span={12}><Form.Item label="启动前审批" name="requiresApproval" valuePropName="checked"><Switch /></Form.Item></Col></Row></Form></Modal>;
}

export function AgentDrawer({ open, onClose, onCreate }: { open: boolean; onClose: () => void; onCreate: (values: AgentFormValues) => void | Promise<void> }) {
  const [form] = Form.useForm<AgentFormValues>();
  return <Drawer title="创建 Agent" open={open} onClose={onClose} size={520} extra={<Button type="primary" onClick={() => form.submit()}>保存</Button>} destroyOnHidden><Form form={form} layout="vertical" initialValues={{ runtime: "Codex", model: "gpt-5.4", permissionProfile: "collaborative", skillIds: ["web-access"], knowledgeScope: "项目知识库" }} onFinish={(values) => { void onCreate(values); form.resetFields(); }}><Form.Item label="名称" name="name" rules={[{ required: true }]}><Input /></Form.Item><Form.Item label="说明" name="description" rules={[{ required: true }]}><Input.TextArea rows={3} /></Form.Item><Row gutter={12}><Col span={12}><Form.Item label="Runtime" name="runtime"><Select options={["Codex", "OpenCode", "BrowserOps", "GenericAgent"].map(option)} /></Form.Item></Col><Col span={12}><Form.Item label="模型" name="model"><Select options={["gpt-5.5", "gpt-5.4", "gpt-5.4-mini"].map(option)} /></Form.Item></Col></Row><Form.Item label="系统提示词" name="systemPrompt"><Input.TextArea rows={5} /></Form.Item><Form.Item label="绑定 Skills" name="skillIds"><Select mode="multiple" options={["web-access", "content-planner", "code-review", "artifact-export"].map(option)} /></Form.Item><Form.Item label="知识范围" name="knowledgeScope"><Input /></Form.Item><Form.Item label="权限策略" name="permissionProfile"><Radio.Group optionType="button"><Radio value="strict">保守</Radio><Radio value="collaborative">协作</Radio><Radio value="auto">自动化</Radio></Radio.Group></Form.Item></Form></Drawer>;
}

export function AgentTeamDrawer({ open, agents, onClose, onCreate }: { open: boolean; agents: AgentRecord[]; onClose: () => void; onCreate: (values: AgentTeamFormValues) => void | Promise<void> }) {
  const [form] = Form.useForm<AgentTeamFormValues>();
  return <Drawer title="创建 Agent Team" open={open} onClose={onClose} size={520} extra={<Button type="primary" onClick={() => form.submit()}>保存 Team</Button>} destroyOnHidden><Form form={form} layout="vertical" initialValues={{ workflow: "lead_sequential", agentIds: agents.slice(0, 2).map((item) => item.key) }} onFinish={(values) => { void onCreate(values); form.resetFields(); }}><Form.Item label="名称" name="name" rules={[{ required: true }]}><Input /></Form.Item><Form.Item label="说明" name="description"><Input.TextArea rows={3} /></Form.Item><Form.Item label="工作流" name="workflow"><Select options={["lead_sequential", "review_chain", "publish_handoff"].map(option)} /></Form.Item><Form.Item label="成员顺序" name="agentIds"><Select mode="multiple" options={agents.map((item) => ({ value: item.key, label: item.name }))} /></Form.Item></Form></Drawer>;
}

export function KnowledgeDrawer({ open, onClose, onCreate }: { open: boolean; onClose: () => void; onCreate: (values: KnowledgeFormValues) => void | Promise<void> }) {
  const [form] = Form.useForm<KnowledgeFormValues>();
  return <Drawer title="新增知识条目" open={open} onClose={onClose} size={520} extra={<Button type="primary" onClick={() => form.submit()}>保存草稿</Button>} destroyOnHidden><Form form={form} layout="vertical" initialValues={{ type: "SOP", visibility: "project", tags: ["审核"] }} onFinish={(values) => { void onCreate(values); form.resetFields(); }}><Form.Item label="标题" name="title" rules={[{ required: true }]}><Input /></Form.Item><Row gutter={12}><Col span={12}><Form.Item label="类型" name="type"><Select options={["SOP", "品牌", "平台规则", "决策", "代码文档"].map(option)} /></Form.Item></Col><Col span={12}><Form.Item label="可见范围" name="visibility"><Select options={[{ value: "project", label: "项目" }, { value: "team", label: "团队" }]} /></Form.Item></Col></Row><Form.Item label="标签" name="tags"><Select mode="tags" /></Form.Item><Form.Item label="正文" name="content" rules={[{ required: true }]}><Input.TextArea rows={8} /></Form.Item></Form></Drawer>;
}

export function ConnectorDrawer({ open, kind, agents, onClose, onCreate }: { open: boolean; kind: ConnectorKind; agents: AgentRecord[]; onClose: () => void; onCreate: (kind: ConnectorKind, values: ConnectorFormValues) => void | Promise<void> }) {
  const [form] = Form.useForm<ConnectorFormValues>();
  return <Drawer title={kind === "MCP" ? "添加 MCP Server" : "注册 CLI Command"} open={open} onClose={onClose} size={520} extra={<Button type="primary" onClick={() => form.submit()}>注册</Button>} destroyOnHidden><Form form={form} layout="vertical" initialValues={{ risk: kind === "MCP" ? "medium" : "low", binding: agents[0]?.name, command: kind === "MCP" ? "github-mcp-server stdio" : "pnpm build" }} onFinish={(values) => { void onCreate(kind, values); form.resetFields(); }}><Form.Item label="名称" name="name" rules={[{ required: true }]}><Input /></Form.Item><Form.Item label="命令 / URL" name="command" rules={[{ required: true }]}><Input /></Form.Item><Form.Item label="说明" name="description" rules={[{ required: true }]}><Input.TextArea rows={3} /></Form.Item><Row gutter={12}><Col span={12}><Form.Item label="风险等级" name="risk"><Select options={[{ value: "low", label: "低风险" }, { value: "medium", label: "中风险" }, { value: "high", label: "高风险" }]} /></Form.Item></Col><Col span={12}><Form.Item label="默认绑定" name="binding"><Select options={agents.map((item) => ({ value: item.name, label: item.name }))} /></Form.Item></Col></Row></Form></Drawer>;
}

function option(value: string) { return { value, label: value }; }

