import { Button, Card, Col, Descriptions, Empty, Flex, Progress, Row, Segmented, Space, Statistic, Steps, Table, Tag, Timeline, Typography } from "antd";
import { useMemo, useState } from "react";
import type { ApiRunEvent } from "../../api";
import type { ApprovalRecord, Task, TaskStatus } from "../../domain/workbench";

const { Text, Title } = Typography;
const statusMeta: Record<TaskStatus, { label: string; color: string; progress: number }> = {
  queued: { label: "排队", color: "default", progress: 15 }, approval: { label: "待审批", color: "warning", progress: 35 }, running: { label: "运行中", color: "processing", progress: 65 }, paused: { label: "已暂停", color: "warning", progress: 50 }, done: { label: "已完成", color: "success", progress: 100 }, failed: { label: "失败", color: "error", progress: 100 }, cancelled: { label: "已取消", color: "default", progress: 100 },
};
const risk: Record<string, [string, string]> = { low: ["success", "低风险"], medium: ["warning", "中风险"], high: ["error", "高风险"] };

export function OverviewPage({ tasks, selectedTask, onSelectTask, knowledgeCount, connectorCount, approvals, events, onStatusChange, onAppendEvent, onOpenApprovals, onOpenStudio }: { tasks: Task[]; selectedTask: Task; onSelectTask: (task: Task) => void; knowledgeCount: number; connectorCount: number; approvals: ApprovalRecord[]; events: ApiRunEvent[]; onStatusChange: (id: string, status: TaskStatus) => void | Promise<void>; onAppendEvent: (task: Task) => void; onOpenApprovals: () => void; onOpenStudio: () => void }) {
  const [filter, setFilter] = useState("全部");
  const filtered = useMemo(() => filter === "全部" ? tasks : filter === "审批" ? tasks.filter((item) => item.status === "approval") : filter === "运行" ? tasks.filter((item) => ["queued", "running", "paused"].includes(item.status)) : tasks.filter((item) => item.status === "failed"), [filter, tasks]);
  const columns = [{ title: "任务", dataIndex: "title", render: (_: unknown, record: Task) => <Space orientation="vertical" size={0}><Text strong>{record.title}</Text><Text type="secondary">{record.description}</Text></Space> }, { title: "Owner", dataIndex: "owner", width: 120 }, { title: "Runtime", dataIndex: "runtime", width: 120 }, { title: "状态", dataIndex: "status", width: 96, render: (status: TaskStatus) => <Tag color={statusMeta[status].color}>{statusMeta[status].label}</Tag> }];
  return <Space orientation="vertical" size={16} className="full-width">
    <Row gutter={[16, 16]}>{[["运行中任务", tasks.filter((item) => ["queued", "approval", "running"].includes(item.status)).length], ["今日产物", 24], ["知识条目", knowledgeCount], ["连接器", connectorCount], ["待审批", approvals.filter((item) => item.status === "pending").length]].map(([title, value]) => <Col xs={24} sm={12} lg={title === "待审批" ? 4 : 5} key={String(title)}><Card><Statistic title={title} value={value} /></Card></Col>)}</Row>
    <Row gutter={[16, 16]}><Col xs={24} xl={15}><Card title="任务队列" extra={<Segmented options={["全部", "运行", "审批", "异常"]} value={filter} onChange={(value) => setFilter(String(value))} />}><Table rowKey="key" columns={columns} dataSource={filtered} pagination={false} rowClassName={(record) => record.key === selectedTask.key ? "selected-row" : ""} onRow={(record) => ({ onClick: () => onSelectTask(record) })} /></Card></Col><Col xs={24} xl={9}><Card title={selectedTask.title} extra={<Tag color={statusMeta[selectedTask.status].color}>{statusMeta[selectedTask.status].label}</Tag>}><Descriptions column={1} size="small"><Descriptions.Item label="目标">{selectedTask.target}</Descriptions.Item><Descriptions.Item label="Runtime">{selectedTask.runtime}</Descriptions.Item><Descriptions.Item label="最近更新">{selectedTask.updatedAt}</Descriptions.Item></Descriptions><Progress percent={statusMeta[selectedTask.status].progress} className="top-gap" /><Steps orientation="vertical" current={stepIndex(selectedTask.status)} items={[{ title: "Create", content: "任务创建并写入 run draft" }, { title: "Context", content: "注入 Agent、知识范围和连接器权限" }, { title: "Approval", content: "高风险能力进入审批队列" }, { title: "Artifact", content: "产物写入 manifest" }]} /><TaskActions task={selectedTask} onStatusChange={onStatusChange} /></Card></Col></Row>
    <Row gutter={[16, 16]}><Col xs={24} xl={15}><RunPanel task={selectedTask} events={events} onAppend={onAppendEvent} /></Col><Col xs={24} xl={9}><Card title="审批概览" extra={<Button onClick={onOpenApprovals}>处理</Button>}>{approvals.length ? <div className="list-panel">{approvals.slice(0, 3).map((item) => <div className="list-row" key={item.key}><div><Text strong>{item.title}</Text><Text type="secondary" className="row-meta">{item.reason}</Text></div><Space><Tag color={risk[item.risk][0]}>{risk[item.risk][1]}</Tag><Tag>{item.status}</Tag></Space></div>)}</div> : <Empty description="暂无审批" />}</Card></Col></Row>
    <ArtifactSnapshot onOpen={onOpenStudio} />
  </Space>;
}

function TaskActions({ task, onStatusChange }: { task: Task; onStatusChange: (id: string, status: TaskStatus) => void | Promise<void> }) { return <Flex wrap gap={8} className="task-actions"><Button disabled={!(["running", "queued"] as TaskStatus[]).includes(task.status)} onClick={() => void onStatusChange(task.key, "paused")}>暂停</Button><Button disabled={!(["paused", "approval"] as TaskStatus[]).includes(task.status)} onClick={() => void onStatusChange(task.key, "running")}>继续</Button><Button disabled={!(["failed", "cancelled"] as TaskStatus[]).includes(task.status)} onClick={() => void onStatusChange(task.key, "queued")}>重试</Button><Button danger disabled={task.status === "done" || task.status === "cancelled"} onClick={() => void onStatusChange(task.key, "cancelled")}>停止</Button></Flex>; }
function RunPanel({ task, events, onAppend }: { task: Task; events: ApiRunEvent[]; onAppend: (task: Task) => void }) { const items = events.length ? events.map((event) => ({ color: event.type.includes("error") ? "red" : event.type.includes("approval") ? "gold" : "blue", content: <Space orientation="vertical" size={0}><Text strong>{event.type}</Text><Text type="secondary">{formatPayload(event.payload)}</Text><Text type="secondary">{new Date(event.createdAt).toLocaleTimeString()}</Text></Space> })) : [{ color: "gray", content: task.runId ? "正在等待 SSE 事件…" : "本地临时任务尚未创建持久化 run" }]; return <Card title="运行事件" extra={<Space>{task.runId ? <Tag color="processing">SSE</Tag> : <Tag>Local</Tag>}<Button size="small" disabled={!task.runId} onClick={() => onAppend(task)}>追加测试事件</Button></Space>}><Timeline items={items} /></Card>; }
function ArtifactSnapshot({ onOpen }: { onOpen: () => void }) { return <Card title="Artifact Studio 快照" extra={<Button onClick={onOpen}>打开 Studio</Button>}><Row gutter={[12, 12]}>{[["MD", "draft.md", "正文草稿", "blue"], ["PNG", "cover.png", "封面图", "purple"], ["HTML", "landing.html", "预览可用", "cyan"], ["ZIP", "publish.zip", "发布包", "gold"]].map(([type, name, desc, color]) => <Col xs={24} sm={12} lg={6} key={name}><Card size="small"><Tag color={color}>{type}</Tag><Title level={5}>{name}</Title><Text type="secondary">{desc}</Text></Card></Col>)}</Row></Card>; }
function stepIndex(status: TaskStatus) { if (status === "queued") return 0; if (status === "running" || status === "paused") return 1; if (status === "approval" || status === "failed") return 2; return 3; }
function formatPayload(payload: unknown) { if (!payload || typeof payload !== "object") return String(payload ?? ""); if ("text" in payload && typeof payload.text === "string") return payload.text; return JSON.stringify(payload); }

