import { ApartmentOutlined, AppstoreOutlined, BookOutlined, KeyOutlined, RobotOutlined, SafetyCertificateOutlined } from "@ant-design/icons";
import { Alert, Button, Divider, Empty, Form, Input, InputNumber, Modal, Select, Spin, Switch, Tabs, Tag, Typography, message } from "antd";
import { useState } from "react";
import type { ReactNode } from "react";
import { checkApiConnector, checkApiModelProvider, createApiAgent, createApiAgentTeam, createApiConnector, createApiKnowledgeItem, createApiModelProvider, createApiWorkflow } from "../api";
import type { ApiAgent, ApiAgentTeam, ApiConnector, ApiKnowledgeItem, ApiModelProvider, ApiSkill, ApiWorkflow, ApiWorkflowPlugin } from "../api";

const { Paragraph, Text, Title } = Typography;

export type SettingsCatalog = {
  connectors: ApiConnector[];
  knowledge: ApiKnowledgeItem[];
  skills: ApiSkill[];
  plugins: ApiWorkflowPlugin[];
  workflows: ApiWorkflow[];
  modelProviders: ApiModelProvider[];
};

type SaveAction = (action: () => Promise<unknown>) => Promise<void>;

export default function SettingsDrawer({ open, loading, error, onClose, onRetry, onChanged, agents, teams, catalog }: { open: boolean; loading: boolean; error?: string; onClose: () => void; onRetry: () => void; onChanged: () => Promise<void>; agents: ApiAgent[]; teams: ApiAgentTeam[]; catalog: SettingsCatalog }) {
  const [saving, setSaving] = useState(false);
  const [checkingProviderId, setCheckingProviderId] = useState<string>();
  const riskLabel = { low: "低风险", medium: "中风险", high: "高风险" } as const;
  const capabilities = [...catalog.skills.map((item) => ({ id: item.id, name: item.name, meta: `技能 · ${riskLabel[item.risk]}` })), ...catalog.plugins.map((item) => ({ id: item.id, name: item.name, meta: `插件 · ${item.version}` })), ...catalog.connectors.map((item) => ({ id: item.id, name: item.name, meta: `${item.kind} · ${riskLabel[item.risk]}` }))];
  const save: SaveAction = async (action) => {
    if (saving) return;
    setSaving(true);
    try { await action(); await onChanged(); message.success("设置已保存"); }
    catch { message.error("设置保存失败，请检查输入和本地服务后重试。"); }
    finally { setSaving(false); }
  };
  const checkProvider = async (provider: ApiModelProvider) => {
    if (checkingProviderId) return;
    setCheckingProviderId(provider.id);
    try { await checkApiModelProvider(provider.id); message.success(`${provider.name}：连接成功`); }
    catch { message.error(`${provider.name}：连接失败，请检查地址、模型、密钥和服务状态。`); }
    finally { setCheckingProviderId(undefined); }
  };

  return <Modal title={<div className="settings-modal-title"><Title level={4}>设置</Title><Text type="secondary">管理工作区中的智能体、能力与运行权限</Text></div>} open={open} onCancel={onClose} width={900} centered footer={null} className="settings-modal">
    {error && <Alert className="settings-error" type="error" showIcon title="部分设置加载失败" description={error} action={<Button size="small" onClick={onRetry}>重试</Button>} />}
    <Spin spinning={loading} description="正在读取设置…" className="settings-spin">
      <Tabs tabPlacement="start" items={[
        { key: "agents", label: <TabLabel icon={<RobotOutlined />} text="智能体" />, children: <SettingsPane title="智能体与团队" description="创建可复用的智能体配置，并将多个智能体组织成协作团队。" items={[...agents.map((item) => ({ id: item.id, name: item.name, meta: `${item.runtime} · ${item.model}` })), ...teams.map((item) => ({ id: item.id, name: item.name, meta: `团队 · ${item.members.length} 名成员` }))]} empty="暂无智能体预设"><SettingsFormSection title="添加智能体" description="绑定模型连接、模型与系统提示词"><AgentForm providers={catalog.modelProviders} saving={saving} save={save} /></SettingsFormSection><SettingsFormSection title="添加团队" description="组合现有智能体完成多步骤任务"><TeamForm agents={agents} saving={saving} save={save} /></SettingsFormSection></SettingsPane> },
        { key: "capabilities", label: <TabLabel icon={<AppstoreOutlined />} text="能力" />, children: <SettingsPane title="技能、插件与连接器" description="管理智能体可以调用的本地工具和外部连接。" items={capabilities} empty="未发现可用能力"><SettingsFormSection title="添加连接器" description="登记 CLI 命令或 MCP 服务端点"><ConnectorForm saving={saving} save={save} /></SettingsFormSection>{catalog.connectors.length > 0 && <div className="connector-checks">{catalog.connectors.map((item) => <Button key={item.id} loading={saving} onClick={() => void save(async () => { const result = await checkApiConnector(item.id); message[result.ok ? "success" : "error"](`${item.name}：${result.status}`); })}>检查 {item.name}</Button>)}</div>}</SettingsPane> },
        { key: "knowledge", label: <TabLabel icon={<BookOutlined />} text="知识库" />, children: <SettingsPane title="项目知识" description="保存当前工作区可复用的规范、背景资料和操作说明。" items={catalog.knowledge.map((item) => ({ id: item.id, name: item.title, meta: `${item.type} · ${item.status}` }))} empty="暂无知识条目"><SettingsFormSection title="添加知识条目" description="将一段内容加入项目知识库"><KnowledgeForm saving={saving} save={save} /></SettingsFormSection></SettingsPane> },
        { key: "workflows", label: <TabLabel icon={<ApartmentOutlined />} text="工作流" />, children: <SettingsPane title="工作流" description="把稳定的多步骤操作保存成可以重复运行的流程。" items={catalog.workflows.map((item) => ({ id: item.id, name: item.name, meta: `${item.steps.length} 个步骤 · ${item.provider}` }))} empty="暂无工作流"><SettingsFormSection title="添加工作流" description="定义起始任务、执行器与并发数"><WorkflowForm saving={saving} save={save} /></SettingsFormSection></SettingsPane> },
        { key: "models", label: <TabLabel icon={<KeyOutlined />} text="模型连接" />, children: <SettingsPane title="OpenAI 兼容连接" description="配置 Chat Completions 服务地址、默认模型和 API Key。" items={catalog.modelProviders.map((item) => ({ id: item.id, name: `${item.name}${item.isDefault ? " · 默认" : ""}`, meta: `${item.defaultModel} · ${item.baseUrl} · ${credentialLabel(item.credentialStatus)}` }))} empty="尚未配置模型连接"><SettingsFormSection title="添加模型连接" description="接入云端或本地 OpenAI 兼容服务"><Alert className="model-credential-alert" type="info" showIcon title="API Key 仅保存在本机" description="凭据保存在权限受限的本地文件中，不写入 SQLite，也不会通过设置接口返回。" /><ModelProviderForm saving={saving} save={save} /></SettingsFormSection>{catalog.modelProviders.length > 0 && <div className="connector-checks">{catalog.modelProviders.map((item) => <Button key={item.id} loading={checkingProviderId === item.id} disabled={Boolean(checkingProviderId && checkingProviderId !== item.id)} onClick={() => void checkProvider(item)}>测试 {item.name}</Button>)}</div>}</SettingsPane> },
        { key: "permissions", label: <TabLabel icon={<SafetyCertificateOutlined />} text="权限" />, children: <PermissionsPane /> },
      ]} />
    </Spin>
  </Modal>;
}

function TabLabel({ icon, text }: { icon: ReactNode; text: string }) { return <span className="settings-tab-label">{icon}<span>{text}</span></span>; }
function SettingsPane({ title, description, items, empty, children }: { title: string; description: string; items: Array<{ id: string; name: string; meta: string }>; empty: string; children: ReactNode }) { return <section className="settings-pane"><header className="settings-pane-header"><Title level={4}>{title}</Title><Paragraph type="secondary">{description}</Paragraph></header><div className="settings-section-heading"><Text strong>当前配置</Text><Text type="secondary">{items.length} 项</Text></div><SettingsList items={items} empty={empty} /><Divider /><div className="settings-section-heading"><Text strong>添加配置</Text></div><div className="settings-actions">{children}</div></section>; }
function SettingsFormSection({ title, description, children }: { title: string; description: string; children: ReactNode }) { return <details className="settings-form-section"><summary><span><Text strong>{title}</Text><Text type="secondary">{description}</Text></span></summary><div className="settings-form-content">{children}</div></details>; }
function PermissionsPane() { return <section className="settings-pane"><header className="settings-pane-header"><Title level={4}>执行权限</Title><Paragraph type="secondary">控制智能体在工作区中执行操作前是否需要你的确认。</Paragraph></header><div className="permission-list"><div><span><Text strong>可写工作区</Text><Text type="secondary">低风险操作自动执行，中高风险操作仍会请求确认。</Text></span><Tag color="green">默认</Tag></div><div><span><Text strong>操作前询问</Text><Text type="secondary">所有可能修改工作区的操作都会先暂停并询问。</Text></span><Tag>严格</Tag></div></div><Alert type="info" showIcon title="审批会显示在当前对话中" description="需要你决策的操作不会被隐藏到活动日志里。" /></section>; }
function AgentForm({ providers, saving, save }: { providers: ApiModelProvider[]; saving: boolean; save: SaveAction }) { const [form] = Form.useForm(); const defaultProvider = providers.find((item) => item.isDefault) ?? providers[0]; const selectedProviderId = Form.useWatch("modelProviderId", form); const selectedProvider = providers.find((item) => item.id === selectedProviderId) ?? defaultProvider; return <Form form={form} key={defaultProvider?.id ?? "no-provider"} layout="vertical" onFinish={(value) => save(() => createApiAgent({ ...value, model: value.model ?? "", skillIds: [], knowledgeScope: "项目知识库", permissionProfile: "collaborative", systemPrompt: value.systemPrompt ?? "" }))} initialValues={{ runtime: "Codex", modelProviderId: defaultProvider?.id }}><Form.Item label="名称" name="name" rules={[{ required: true, message: "请输入智能体名称" }]}><Input maxLength={80} /></Form.Item><Form.Item label="说明" name="description" rules={[{ required: true, message: "请输入用途说明" }]}><Input maxLength={240} /></Form.Item><div className="form-grid"><Form.Item label="运行时" name="runtime"><Select options={["Codex", "OpenCode", "BrowserOps"].map((value) => ({ value }))} /></Form.Item><Form.Item label="模型连接" name="modelProviderId" rules={[{ required: true, message: "请选择模型连接" }]}><Select placeholder="先添加模型连接" options={providers.map((item) => ({ value: item.id, label: item.name }))} /></Form.Item></div><Form.Item label="模型" name="model" help={`留空时使用 ${selectedProvider?.defaultModel ?? "连接默认模型"}`}><Input maxLength={120} placeholder={selectedProvider?.defaultModel ?? "模型标识"} /></Form.Item><Form.Item label="系统提示词" name="systemPrompt"><Input.TextArea rows={3} maxLength={8000} showCount /></Form.Item><Button type="primary" htmlType="submit" loading={saving} disabled={!providers.length}>添加智能体</Button></Form>; }
function TeamForm({ agents, saving, save }: { agents: ApiAgent[]; saving: boolean; save: SaveAction }) { return <Form layout="vertical" onFinish={(value) => save(() => createApiAgentTeam({ name: value.name, description: value.description ?? "", workflow: "lead_sequential", members: (value.agentIds ?? []).map((agentId: string, order: number) => ({ agentId, role: order ? "执行" : "负责人", order })) }))}><Form.Item label="团队名称" name="name" rules={[{ required: true, message: "请输入团队名称" }]}><Input maxLength={80} /></Form.Item><Form.Item label="成员" name="agentIds" rules={[{ required: true, message: "请选择至少一个成员" }]}><Select mode="multiple" options={agents.map((item) => ({ value: item.id, label: item.name }))} /></Form.Item><Form.Item label="说明" name="description"><Input maxLength={240} /></Form.Item><Button htmlType="submit" loading={saving} disabled={!agents.length}>添加团队</Button></Form>; }
function ConnectorForm({ saving, save }: { saving: boolean; save: SaveAction }) { return <Form layout="vertical" initialValues={{ kind: "CLI", risk: "medium", binding: "workspace" }} onFinish={(value) => save(() => createApiConnector(value))}><div className="form-grid"><Form.Item label="名称" name="name" rules={[{ required: true, message: "请输入连接器名称" }]}><Input maxLength={80} /></Form.Item><Form.Item label="类型" name="kind"><Select options={["CLI", "MCP"].map((value) => ({ value }))} /></Form.Item></div><Form.Item label="命令或端点" name="command" rules={[{ required: true, message: "请输入命令或 MCP 端点" }]}><Input maxLength={1000} /></Form.Item><Form.Item label="说明" name="description" rules={[{ required: true, message: "请输入用途说明" }]}><Input maxLength={240} /></Form.Item><div className="form-grid"><Form.Item label="风险等级" name="risk"><Select options={[{ value: "low", label: "低" }, { value: "medium", label: "中" }, { value: "high", label: "高" }]} /></Form.Item><Form.Item label="绑定范围" name="binding"><Input maxLength={120} /></Form.Item></div><Button type="primary" htmlType="submit" loading={saving}>添加连接器</Button></Form>; }
function KnowledgeForm({ saving, save }: { saving: boolean; save: SaveAction }) { return <Form layout="vertical" initialValues={{ type: "SOP", visibility: "project" }} onFinish={(value) => save(() => createApiKnowledgeItem({ ...value, tags: String(value.tags ?? "").split(/[,，]/).map((tag) => tag.trim()).filter(Boolean) }))}><Form.Item label="标题" name="title" rules={[{ required: true, message: "请输入标题" }]}><Input maxLength={120} /></Form.Item><div className="form-grid"><Form.Item label="类型" name="type"><Input maxLength={40} /></Form.Item><Form.Item label="标签" name="tags" help="用逗号分隔"><Input maxLength={240} /></Form.Item></div><Form.Item label="内容" name="content" rules={[{ required: true, message: "请输入知识内容" }]}><Input.TextArea rows={5} maxLength={20000} showCount /></Form.Item><Form.Item name="visibility" hidden><Input /></Form.Item><Button type="primary" htmlType="submit" loading={saving}>添加知识条目</Button></Form>; }
function WorkflowForm({ saving, save }: { saving: boolean; save: SaveAction }) { return <Form layout="vertical" initialValues={{ provider: "codex-cli", concurrency: 1 }} onFinish={(value) => save(() => createApiWorkflow({ name: value.name, description: value.description ?? "", provider: value.provider, concurrency: value.concurrency, tags: [], steps: [{ id: "step_1", role: "执行者", task: value.task, dependsOn: [] }] }))}><Form.Item label="名称" name="name" rules={[{ required: true, message: "请输入工作流名称" }]}><Input maxLength={80} /></Form.Item><Form.Item label="说明" name="description"><Input maxLength={240} /></Form.Item><Form.Item label="首个步骤任务" name="task" rules={[{ required: true, message: "请输入步骤任务" }]}><Input.TextArea rows={3} maxLength={4000} showCount /></Form.Item><div className="form-grid"><Form.Item label="执行器" name="provider"><Input maxLength={80} /></Form.Item><Form.Item label="并发数" name="concurrency"><InputNumber min={1} max={16} /></Form.Item></div><Button type="primary" htmlType="submit" loading={saving}>添加工作流</Button></Form>; }
function ModelProviderForm({ saving, save }: { saving: boolean; save: SaveAction }) { return <Form layout="vertical" initialValues={{ noAuth: false, isDefault: false }} onFinish={(value) => save(() => createApiModelProvider({ ...value, noAuth: Boolean(value.noAuth), isDefault: Boolean(value.isDefault) }))}><div className="form-grid"><Form.Item label="连接名称" name="name" rules={[{ required: true, message: "请输入连接名称" }]}><Input maxLength={80} placeholder="团队模型服务" /></Form.Item><Form.Item label="默认模型" name="defaultModel" rules={[{ required: true, message: "请输入默认模型" }]}><Input maxLength={120} placeholder="模型标识" /></Form.Item></div><Form.Item label="Base URL" name="baseUrl" help="系统会在该地址后追加 /chat/completions" rules={[{ required: true, message: "请输入 Base URL" }, { type: "url", message: "请输入有效的 HTTP 或 HTTPS 地址" }]}><Input maxLength={1000} placeholder="https://api.example.com/v1" /></Form.Item><Form.Item noStyle shouldUpdate={(previous, current) => previous.noAuth !== current.noAuth}>{({ getFieldValue }) => !getFieldValue("noAuth") ? <Form.Item label="API Key" name="apiKey" rules={[{ required: true, message: "请输入 API Key" }]}><Input.Password autoComplete="new-password" maxLength={1000} placeholder="输入 API Key" /></Form.Item> : null}</Form.Item><div className="form-grid"><Form.Item label="此服务无需 API Key" name="noAuth" valuePropName="checked"><Switch /></Form.Item><Form.Item label="设为默认连接" name="isDefault" valuePropName="checked"><Switch /></Form.Item></div><Button type="primary" htmlType="submit" loading={saving}>添加模型连接</Button></Form>; }
function SettingsList({ items, empty }: { items: Array<{ id: string; name: string; meta: string }>; empty: string }) { return items.length ? <div className="settings-list">{items.map((item) => <div key={item.id}><Text strong>{item.name}</Text><Text type="secondary">{item.meta}</Text></div>)}</div> : <Empty image={Empty.PRESENTED_IMAGE_SIMPLE} description={empty} />; }
function credentialLabel(status: ApiModelProvider["credentialStatus"]) { return status === "available" ? "密钥可用" : status === "not_required" ? "无需密钥" : "未配置密钥"; }
