import { CheckCircleOutlined } from "@ant-design/icons";
import { Button, Card, Col, Form, Input, Radio, Row, Select, Space, Switch, Table, Tag, Typography } from "antd";
import type { SecretFormValues, SecretRecord } from "../../domain/workbench";

const { Text } = Typography;

export function SettingsPage({ secrets, onCreateSecret }: { secrets: SecretRecord[]; onCreateSecret: (values: SecretFormValues) => void | Promise<void> }) {
  const [form] = Form.useForm<SecretFormValues>();
  return <Space orientation="vertical" size={16} className="full-width"><Row gutter={[16, 16]}><Col xs={24} xl={12}><Card title="模型与 Runtime"><div className="list-panel">{["Codex CLI", "OpenCode", "GenericAgent Worker"].map((item, index) => <div className="list-row" key={item}><div><Text strong>{item}</Text><Text type="secondary" className="row-meta">{index === 2 ? "127.0.0.1:3917" : "已连接"}</Text></div><Switch defaultChecked={index < 2} /></div>)}</div></Card></Col><Col xs={24} xl={12}><Card title="安全策略"><Radio.Group defaultValue="collab" optionType="button" buttonStyle="solid"><Radio value="auto">自动化</Radio><Radio value="collab">协作</Radio><Radio value="strict">保守</Radio></Radio.Group><div className="list-panel top-gap">{["插件安装：需要确认", "真实账号发布：禁止自动提交", "Secret 只登记环境变量引用", "团队权限按 Agent/Team 绑定范围执行"].map((item) => <div className="list-row" key={item}><Text>{item}</Text><CheckCircleOutlined className="success-icon" /></div>)}</div></Card></Col></Row><Row gutter={[16, 16]}><Col xs={24} xl={12}><Card title="Secret 管理"><Form form={form} layout="vertical" initialValues={{ scope: "runtime", envVar: "OPENAI_API_KEY" }} onFinish={(values) => { void onCreateSecret(values); form.resetFields(); }}><Row gutter={12}><Col xs={24} md={10}><Form.Item label="名称" name="name" rules={[{ required: true, message: "请输入名称" }]}><Input placeholder="OpenAI API Key…" /></Form.Item></Col><Col xs={24} sm={12} md={7}><Form.Item label="Scope" name="scope"><Select options={["runtime", "mcp", "publishing", "team"].map((value) => ({ value, label: value }))} /></Form.Item></Col><Col xs={24} sm={12} md={7}><Form.Item label="环境变量" name="envVar" rules={[{ required: true, message: "请输入环境变量名" }]}><Input /></Form.Item></Col></Row><Button type="primary" onClick={() => form.submit()}>登记 Secret 引用</Button></Form><div className="list-panel top-gap">{secrets.map((secret) => <div className="list-row" key={secret.key}><div><Text strong>{secret.name}</Text><Text type="secondary" className="row-meta">{secret.valuePreview}</Text></div><Space wrap><Tag>{secret.scope}</Tag><Tag color={secret.status === "available" ? "success" : "warning"}>{secret.status === "available" ? "可用" : "缺失"}</Tag></Space></div>)}</div></Card></Col><Col xs={24} xl={12}><Card title="团队权限隔离"><Table rowKey="role" pagination={false} columns={[{ title: "角色", dataIndex: "role" }, { title: "默认权限", dataIndex: "policy" }, { title: "审批", dataIndex: "approval", render: (value) => <Tag color={value ? "warning" : "success"}>{value ? "需要" : "自动"}</Tag> }]} dataSource={[{ role: "Owner", policy: "管理 Agent、Team、Secret 和连接器", approval: false }, { role: "Operator", policy: "运行任务、处理低风险 CLI、登记 Artifact", approval: false }, { role: "Reviewer", policy: "审批中高风险 MCP / CLI / 发布动作", approval: true }, { role: "Viewer", policy: "只读任务、知识库和产物", approval: false }]} /></Card></Col></Row></Space>;
}

