export function createRowMappers(listTeamMembers, hasModelCredential = () => false) {
  return {
    taskFromRow: (row) => ({ id: row.id, runId: row.run_id, title: row.title, prompt: row.prompt, targetType: row.target_type, targetId: row.target_id, owner: row.owner, runtime: row.runtime, status: row.status, priority: row.priority, requiresApproval: Boolean(row.requires_approval), createdAt: row.created_at, updatedAt: row.updated_at }),
    agentFromRow: (row) => ({ id: row.id, name: row.name, description: row.description, runtime: row.runtime, modelProviderId: row.model_provider_id, model: row.model, systemPrompt: row.system_prompt, skillIds: JSON.parse(row.skill_ids), knowledgeScope: row.knowledge_scope, permissionProfile: row.permission_profile, status: row.status, createdAt: row.created_at, updatedAt: row.updated_at }),
    knowledgeFromRow: (row) => ({ id: row.id, title: row.title, type: row.type, content: row.content, tags: JSON.parse(row.tags), visibility: row.visibility, status: row.status, sourceUrl: row.source_url, createdAt: row.created_at, updatedAt: row.updated_at }),
    connectorFromRow: (row) => ({ id: row.id, kind: row.kind, name: row.name, description: row.description, command: row.command, risk: row.risk, binding: row.binding, status: row.status, createdAt: row.created_at, updatedAt: row.updated_at }),
    approvalFromRow: (row) => ({ id: row.id, taskId: row.task_id, title: row.title, source: row.source, risk: row.risk, capabilities: JSON.parse(row.capabilities), status: row.status, reason: row.reason, createdAt: row.created_at, updatedAt: row.updated_at }),
    teamFromRow: (row) => ({ id: row.id, name: row.name, workflow: row.workflow, description: row.description, status: row.status, members: listTeamMembers.all(row.id).map((member) => ({ agentId: member.agent_id, role: member.role, order: member.member_order })), createdAt: row.created_at, updatedAt: row.updated_at }),
    artifactFromRow: (row) => ({ id: row.id, taskId: row.task_id, runId: row.run_id, name: row.name, kind: row.kind, summary: row.summary, source: row.source, path: row.path, manifest: JSON.parse(row.manifest), createdAt: row.created_at, updatedAt: row.updated_at }),
    workflowFromRow: (row) => ({ id: row.id, name: row.name, description: row.description, provider: row.provider, concurrency: row.concurrency, tags: JSON.parse(row.tags), steps: JSON.parse(row.steps), status: row.status, createdAt: row.created_at, updatedAt: row.updated_at }),
    artifactVersionFromRow: (row) => ({ id: row.id, artifactId: row.artifact_id, version: row.version, path: row.path, summary: row.summary, contentType: row.content_type, bytes: row.bytes, createdAt: row.created_at }),
    modelProviderFromRow: (row) => ({ id: row.id, name: row.name, baseUrl: row.base_url, requiresApiKey: row.auth_type === "bearer", defaultModel: row.default_model, isDefault: Boolean(row.is_default), enabled: Boolean(row.enabled), credentialStatus: row.auth_type === "none" ? "not_required" : hasModelCredential(row.id) ? "available" : "missing", createdAt: row.created_at, updatedAt: row.updated_at }),
    eventFromRow: (row) => ({ id: row.id, runId: row.run_id, type: row.type, payload: JSON.parse(row.payload), createdAt: row.created_at }),
  };
}
