export function createStatements(db) {
  return {
    insertTask: db.prepare(`INSERT INTO tasks (id, title, prompt, target_type, target_id, owner, runtime, status, priority, requires_approval, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`),
    insertRun: db.prepare(`INSERT INTO runs (id, task_id, status, started_at, completed_at, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?)`),
    insertEvent: db.prepare(`INSERT INTO events (id, run_id, type, payload, created_at) VALUES (?, ?, ?, ?, ?)`),
    listTasks: db.prepare(`SELECT tasks.*, runs.id AS run_id FROM tasks LEFT JOIN runs ON runs.task_id = tasks.id ORDER BY tasks.created_at DESC`),
    listEvents: db.prepare("SELECT * FROM events WHERE run_id = ? ORDER BY created_at ASC"),
    getRun: db.prepare("SELECT * FROM runs WHERE id = ?"),
    getTask: db.prepare("SELECT * FROM tasks WHERE id = ?"),
    getLatestRunByTask: db.prepare("SELECT * FROM runs WHERE task_id = ? ORDER BY created_at DESC LIMIT 1"),
    getPendingApprovalByTask: db.prepare("SELECT * FROM approvals WHERE task_id = ? AND status = 'pending' ORDER BY created_at DESC LIMIT 1"),
    updateTaskStatusStatement: db.prepare("UPDATE tasks SET status = ?, updated_at = ? WHERE id = ?"),
    updateRunStatusStatement: db.prepare("UPDATE runs SET status = ?, updated_at = ?, completed_at = ? WHERE id = ?"),
    insertAgent: db.prepare(`INSERT INTO agents (id, name, description, runtime, model, system_prompt, skill_ids, knowledge_scope, permission_profile, status, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`),
    listAgents: db.prepare("SELECT * FROM agents ORDER BY created_at DESC"),
    updateAgentStatusStatement: db.prepare("UPDATE agents SET status = ?, updated_at = ? WHERE id = ?"),
    insertKnowledgeItem: db.prepare(`INSERT INTO knowledge_items (id, title, type, content, tags, visibility, status, source_url, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`),
    listKnowledgeItems: db.prepare("SELECT * FROM knowledge_items ORDER BY created_at DESC"),
    insertConnector: db.prepare(`INSERT INTO connectors (id, kind, name, description, command, risk, binding, status, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`),
    listConnectors: db.prepare("SELECT * FROM connectors ORDER BY created_at DESC"),
    updateConnectorStatusStatement: db.prepare("UPDATE connectors SET status = ?, updated_at = ? WHERE id = ?"),
    getConnector: db.prepare("SELECT * FROM connectors WHERE id = ?"),
    getTeam: db.prepare("SELECT * FROM agent_teams WHERE id = ?"),
    insertApproval: db.prepare(`INSERT INTO approvals (id, task_id, title, source, risk, capabilities, status, reason, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`),
    listApprovals: db.prepare("SELECT * FROM approvals ORDER BY created_at DESC"),
    listApprovalsByStatus: db.prepare("SELECT * FROM approvals WHERE status = ? ORDER BY created_at DESC"),
    getApproval: db.prepare("SELECT * FROM approvals WHERE id = ?"),
    updateApprovalStatusStatement: db.prepare("UPDATE approvals SET status = ?, updated_at = ? WHERE id = ?"),
    insertPendingCapabilityExecution: db.prepare(`INSERT INTO pending_capability_executions (approval_id, capability_id, input, context, status, created_at, updated_at) VALUES (?, ?, ?, ?, 'pending', ?, ?)`),
    getPendingCapabilityExecution: db.prepare("SELECT * FROM pending_capability_executions WHERE approval_id = ? AND status = 'pending'"),
    completePendingCapabilityExecution: db.prepare("UPDATE pending_capability_executions SET status = ?, result = ?, error = ?, updated_at = ? WHERE approval_id = ?"),
    insertTeam: db.prepare(`INSERT INTO agent_teams (id, name, workflow, description, status, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?)`),
    insertTeamMember: db.prepare(`INSERT INTO agent_team_members (team_id, agent_id, role, member_order) VALUES (?, ?, ?, ?)`),
    listTeams: db.prepare("SELECT * FROM agent_teams ORDER BY created_at DESC"),
    listTeamMembers: db.prepare("SELECT * FROM agent_team_members WHERE team_id = ? ORDER BY member_order ASC"),
    insertArtifact: db.prepare(`INSERT INTO artifacts (id, task_id, run_id, name, kind, summary, source, path, manifest, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`),
    listArtifacts: db.prepare("SELECT * FROM artifacts ORDER BY created_at DESC"),
    getArtifact: db.prepare("SELECT * FROM artifacts WHERE id = ?"),
    updateArtifactPathStatement: db.prepare("UPDATE artifacts SET path = ?, updated_at = ? WHERE id = ?"),
    insertArtifactVersion: db.prepare(`INSERT INTO artifact_versions (id, artifact_id, version, path, summary, content_type, bytes, created_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?)`),
    listArtifactVersions: db.prepare("SELECT * FROM artifact_versions WHERE artifact_id = ? ORDER BY version DESC"),
    getLatestArtifactVersion: db.prepare("SELECT * FROM artifact_versions WHERE artifact_id = ? ORDER BY version DESC LIMIT 1"),
    countArtifactVersions: db.prepare("SELECT COUNT(*) AS count FROM artifact_versions WHERE artifact_id = ?"),
    insertWorkflow: db.prepare(`INSERT INTO workflows (id, name, description, provider, concurrency, tags, steps, status, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`),
    listWorkflows: db.prepare("SELECT * FROM workflows ORDER BY created_at DESC"),
    getWorkflow: db.prepare("SELECT * FROM workflows WHERE id = ?"),
    insertSecret: db.prepare(`INSERT INTO secrets (id, name, scope, env_var, status, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?)`),
    listSecrets: db.prepare("SELECT * FROM secrets ORDER BY created_at DESC"),
    deleteSecret: db.prepare("DELETE FROM secrets WHERE id = ?"),
  };
}
